const MoviesActionTypes={
    UPDATE_LIST: 'UPDATE_LIST',
    UPDATE_SEARCH: 'UPDATE_SEARCH',
    ADD_NOMINATION: 'ADD_NOMINATION',
    REMOVE_NOMINATION: 'REMOVE_NOMINATION',
    EMPTY_MOVIES: 'EMPTY_MOVIES'
}

export default MoviesActionTypes;